#!/usr/bin/env python3
"""Reproduce the versioned CRC case study using data outside this Git repo.

The original published-analysis scripts are frozen under legacy/scripts and
panel/. This entry point stages code into a work root containing raw data,
injects paths supplied by the CLI, runs requested phases, and writes a run
manifest. No machine-specific path is committed to Git.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

CASE = Path(__file__).resolve().parent
REPO = CASE.parents[1]
PANELS = (
    "01_MHC_I_correlation",
    "02_T_cell_state_correlation",
    "03_tumor_treatment_trajectories",
)
IDENTITY_FILES = (
    "audit/geo_downloads.json", "audit/official_sample_tables.csv",
    "audit/scct_crc_samples.csv", "audit/cellchat_fingerprints.json",
    "panel/01_MHC_I_correlation/source/input_manifest.csv",
    "panel/02_T_cell_state_correlation/source/input_manifest.csv",
    "panel/03_tumor_treatment_trajectories/source/input_manifest.csv",
)


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def stage_file(src: Path, dst: Path, staged: list[dict]) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    changed = not dst.exists() or digest(src) != digest(dst)
    if changed:
        shutil.copy2(src, dst)
    staged.append({"path": str(dst), "sha256": digest(src), "updated": changed})


def stage_code(root: Path) -> list[dict]:
    staged: list[dict] = []
    for src in (CASE / "legacy" / "scripts").iterdir():
        if src.is_file():
            stage_file(src, root / "scripts" / src.name, staged)
    for src in (CASE / "panel").rglob("*"):
        if src.is_file():
            stage_file(src, root / "panel" / src.relative_to(CASE / "panel"), staged)
    stage_file(CASE / "cellchat_config.json", root / "cellchat_config.json", staged)
    return staged


def executable(value: str | None, fallback: str) -> str | None:
    if value:
        return str(Path(value).expanduser().resolve()) if Path(value).exists() else shutil.which(value)
    return shutil.which(fallback)


def cli() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--work-root", type=Path, required=True,
                   help="external CRC work directory containing data/, audit/, derived/")
    p.add_argument("--source-dir", type=Path,
                   help="downloaded CellResDB/scCT-DB source directory; required for full preparation")
    p.add_argument("--mode", choices=("stage", "panels-plot", "panels", "legacy-figures",
                                      "legacy-full", "install-cellchat", "cellchat", "all", "validate"), default="stage")
    p.add_argument("--rscript", help="Rscript executable; defaults to PATH or existing run config")
    p.add_argument("--python", help="Python executable; defaults to this interpreter")
    p.add_argument("--node", help="Node executable; defaults to PATH or existing run config")
    p.add_argument("--workers", type=int, default=4, help="CellChat parallel sample jobs (1–6)")
    p.add_argument("--download-missing", action="store_true",
                   help="run the frozen GEO/portal download audit before full preparation")
    p.add_argument("--install-cellchat", action="store_true",
                   help="install pinned CellChat runtime before cellchat/all mode")
    p.add_argument("--run-name", help="manifest filename stem; autogenerated when omitted")
    return p.parse_args()


def main() -> None:
    args = cli()
    root = args.work_root.expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    for folder in ("audit", "derived", "tables", "figures"):
        (root / folder).mkdir(exist_ok=True)
    old_config_path = root / "analysis_config.json"
    old_paths = json.loads(old_config_path.read_text(encoding="utf-8")).get("paths", {}) if old_config_path.exists() else {}
    source = args.source_dir.expanduser().resolve() if args.source_dir else Path(old_paths["source_dir"]).resolve() if old_paths.get("source_dir") else None
    rscript = executable(args.rscript or old_paths.get("Rscript"), "Rscript")
    node = executable(args.node or old_paths.get("node"), "node")
    python = executable(args.python or old_paths.get("python"), "python") if (args.python or old_paths.get("python")) else sys.executable
    staged = stage_code(root)
    needs_r = args.mode in ("panels-plot", "panels", "legacy-figures", "legacy-full",
                            "install-cellchat", "cellchat", "all", "validate")
    needs_node = args.mode in ("legacy-full", "cellchat", "all")
    if needs_r and not rscript:
        raise SystemExit("Rscript is required; pass --rscript")
    if needs_node and not node:
        raise SystemExit("Node is required; pass --node")
    if not python:
        raise SystemExit("Python is required; pass --python")
    if args.mode in ("legacy-full", "all") and (source is None or not source.is_dir()):
        raise SystemExit("full preparation requires --source-dir pointing to downloaded portal data")
    parameters = json.loads((CASE / "analysis_parameters.json").read_text(encoding="utf-8"))
    if source:
        parameters["paths"] = {"source_dir": str(source), "Rscript": rscript,
                                "python": python, "node": node}
        old_config_path.write_text(json.dumps(parameters, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    run_name = args.run_name or f"{stamp}_{args.mode}"
    run_dir = root / "audit" / "runs" / run_name
    run_dir.mkdir(parents=True, exist_ok=False)
    git_commit = os.getenv("PDA_REPLAY_GIT_COMMIT")
    if not git_commit:
        try:
            git_commit = subprocess.check_output(
                ["git", "-c", f"safe.directory={REPO.as_posix()}", "-C", str(REPO), "rev-parse", "HEAD"],
                text=True, stderr=subprocess.DEVNULL).strip()
        except (OSError, subprocess.CalledProcessError):
            git_commit = None
    manifest = {"schema_version": 1, "mode": args.mode, "started_utc": stamp,
                "command": sys.argv, "git_commit": git_commit,
                "paths": {"work_root": str(root), "source_dir": str(source) if source else None,
                          "rscript": rscript, "python": python, "node": node},
                "parameters": parameters, "staged_code": staged,
                "replay_of": os.getenv("PDA_REPLAY_SOURCE_MANIFEST"),
                "replay_input_changed": os.getenv("PDA_REPLAY_INPUT_CHANGED") == "true",
                "input_identity": {rel: {"bytes": (root / rel).stat().st_size,
                                          "sha256": digest(root / rel)}
                                   for rel in IDENTITY_FILES if (root / rel).is_file()},
                "steps": [], "status": "running"}

    def save_manifest() -> None:
        path = run_dir / "run_manifest.json"
        temporary = path.with_suffix(".tmp")
        temporary.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        temporary.replace(path)

    def run(label: str, command: list[str]) -> None:
        print("RUN", label, flush=True)
        log = run_dir / f"{len(manifest['steps']) + 1:02d}_{label}.log"
        with log.open("w", encoding="utf-8") as stream:
            result = subprocess.run(command, cwd=root, stdout=stream,
                                    stderr=subprocess.STDOUT, check=False)
        manifest["steps"].append({"name": label, "command": command,
                                  "exit_code": result.returncode, "log": str(log)})
        save_manifest()
        if result.returncode:
            raise RuntimeError(f"{label} failed; see {log}")

    def old(name: str, extra: list[str] | None = None) -> None:
        suffix = Path(name).suffix.lower()
        exe = {".r": rscript, ".py": python, ".mjs": node}[suffix]
        run(Path(name).stem, [exe, str(root / "scripts" / name), *(extra or [])])

    def panels(process: bool) -> None:
        for panel in PANELS:
            script_dir = root / "panel" / panel / "script"
            source_dir = root / "panel" / panel / "source"
            figure_dir = root / "panel" / panel / "figure"
            source_dir.mkdir(parents=True, exist_ok=True)
            figure_dir.mkdir(parents=True, exist_ok=True)
            if process:
                run(panel + "_process", [rscript, str(script_dir / "data_processing.R")])
            run(panel + "_plot", [rscript, str(script_dir / "plot.R")])
        run("export_contracts", [python, str(CASE / "export_contracts.py"),
                                 "--work-root", str(root)])
        processed = root / "processed" / "contracts_v1"
        for kind, filename in (("observations", "patient_observations.csv"),
                               ("statistics", "statistical_results.csv")):
            run("validate_" + kind, [python, str(REPO / "processing" / "contracts" / "validate.py"),
                                      "--contract", kind, "--input", str(processed / filename)])

    save_manifest()
    try:
        if args.download_missing:
            if source is None or not source.is_dir():
                raise ValueError("--download-missing requires --source-dir")
            for script in ("05_remote_audit.py", "06_download_missing.py"):
                old(script)
        if args.mode == "install-cellchat" or (args.install_cellchat and args.mode in ("cellchat", "all")):
            old("17_install_cellchat.R")
        if args.mode in ("legacy-full", "all"):
            for script in ("01_audit_archives.py", "02_extract_cellres.R", "03_extract_scct.py",
                           "04_stream_rds.py", "09_clinical_metadata.py", "11_validate_geo205506.py",
                           "12_prepare_geo_metadata.R", "13_extract_geo236581.mjs",
                           "15_finalize_integrity.py"):
                old(script, [str(root)] if script == "02_extract_cellres.R" else
                    ["*Colorectal*.rds"] if script == "04_stream_rds.py" else None)
        if args.mode in ("legacy-full", "legacy-figures", "all"):
            for script in ("07_summarize.R", "08_statistics_figures.R", "14_sensitivity.R"):
                old(script)
        if args.mode in ("cellchat", "all"):
            if not 1 <= args.workers <= 6:
                raise ValueError("--workers must be 1–6")
            for script in ("18_prepare_cellchat.py", "19_extract_cellchat_geo.mjs",
                           "20_extract_cellchat_scct.py", "23_dispatch_cellchat.py",
                           "26_validate_cellchat.R", "22_cellchat_comparison.R",
                           "24_cellchat_report.py", "25_finalize_cellchat_docs.py"):
                old(script, ["--workers", str(args.workers)] if script == "23_dispatch_cellchat.py" else None)
        if args.mode in ("panels", "all"):
            panels(process=True)
        if args.mode == "panels-plot":
            panels(process=False)
        if args.mode == "validate":
            run("panel_numeric_pdf_qa", [python, str(root / "panel" / "03_tumor_treatment_trajectories" / "script" / "validate.py")])
            run("all_figure_geometry_qa", [python, str(CASE / "verify_figures.py"),
                                           "--work-root", str(root)])
            with (CASE / "figure_inventory.csv").open(newline="", encoding="utf-8-sig") as stream:
                inventory = list(csv.DictReader(stream))
            missing = [str(root / rel) for row in inventory for rel in (row["pdf"], row["png"])
                       if not (root / rel).is_file()]
            manifest["figure_inventory"] = {"expected_pdf_png_pairs": len(inventory),
                                             "missing_files": missing}
            if missing:
                raise RuntimeError(f"{len(missing)} expected figure files are missing")
        manifest["status"] = "success"
    except Exception as exc:
        manifest["status"] = "failed"
        manifest["error"] = str(exc)
        raise
    finally:
        manifest["finished_utc"] = datetime.now(timezone.utc).isoformat()
        save_manifest()
    print("DONE", run_dir / "run_manifest.json")


if __name__ == "__main__":
    main()
